// MIT License
//
// Copyright (c) 2021 Gabriele Tripi
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// -------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------
// FILE NAME : reorder_buffer.sv
// DEPARTMENT : 
// AUTHOR : Gabriele Tripi
// AUTHOR'S EMAIL : tripi.gabriele2002@gmail.com
// -------------------------------------------------------------------------------------
// RELEASE HISTORY
// VERSION : 1.0 
// DESCRIPTION : This module contains the code for the reorder buffer, as the name
//               suggest, it reorders the instructions that comes from the execution 
//               unit. From the write port it behave like a normal random access memory.
//               the address is the tag generated by the front-end. The read port 
//               has only the command, infact the address is manged internally. 
//               The ROB has two piece of memory: the memory where the packets get 
//               stored from the execution unit and the valid memory which tells the
//               logic if the current entry is valid or is not. This will generate the
//               valid bit (the read pointer points to the next entry after the read).
//               The writeback stage assert the command only to advance the pointer 
//               because the memory has asyncronous read logic. This module is also
//               responsable of generating valid tag entries for the scheduler.
// -------------------------------------------------------------------------------------

`ifndef REORDER_BUFFER_SV
    `define REORDER_BUFFER_SV

module reorder_buffer #(
    /* Reorder Buffer entries */
    parameter ROB_DEPTH = 32
) (
    input logic clk_i,
    input logic rst_n_i,
    input logic flush_i,
    input logic stall_i,

    /* Scheduler interface */
    input logic rob_alloc_i,
    input data_word_t alloc_pc_i,
    output logic [$clog2(ROB_DEPTH):0] rob_tag_o,

    /* Flush logic */
    input logic branch_flush_i,
    input logic [$clog2(ROB_DEPTH):0] branch_tag_i,

    /* ROB address */
    input logic [$clog2(ROB_DEPTH):0] tag_i,

    /* Reorder buffer entry from memory
     * and computation unit */
    input rob_entry_t entry_i,

    /* Commands */
    input logic write_i,
    input logic read_i,

    /* ROB status */
    output logic full_o,
    output logic empty_o,

    /* The current ROB packet pointed is
     * valid and can be written back */
    output logic valid_o,
    output rob_entry_t entry_o,
    output data_word_t head_pc_o
);

    /* Carry extra info for full/empty */
    localparam PTR_WIDTH = $clog2(ROB_DEPTH) + 1;

    /* Physical index of the memory */
    localparam IDX_WIDTH = $clog2(ROB_DEPTH);


//====================================================================================
//      POINTERS LOGIC
//====================================================================================

    /* To avoid writing multiple times the same result, check if the tag that is being written 
     * is the same of the previous clock cycle */ 
    logic [PTR_WIDTH - 1:0] previous_tag; logic write, previous_tag_valid; 

        always_ff @(posedge clk_i `ifdef ASYNC or negedge rst_n_i `endif) begin
            if (!rst_n_i) begin
                previous_tag <= '0;
                previous_tag_valid <= 1'b0;
            end else if (flush_i | branch_flush_i) begin 
                previous_tag_valid <= 1'b0;
            end else if (write_i) begin 
                previous_tag <= tag_i;
                previous_tag_valid <= 1'b1;
            end 
        end 

    assign write = write_i & !(previous_tag_valid & (previous_tag == tag_i));


    /* Read pointer is managed indirectly by the write back logic by asserting the
     * read command. */
    logic [PTR_WIDTH - 1:0] read_ptr, read_ptr_incremented, read_ptr_next;

    assign read_ptr_incremented = read_ptr + 1'b1;
    assign read_ptr_next = (read_i & !stall_i) ? read_ptr_incremented : read_ptr;

        always_ff @(posedge clk_i `ifdef ASYNC or negedge rst_n_i `endif) begin
            if (!rst_n_i) begin
                read_ptr <= '0;
            end else if (flush_i) begin 
                read_ptr <= '0;
            end else begin
                read_ptr <= read_ptr_next;
            end
        end


//====================================================================================
//      ALLOCATION LOGIC
//====================================================================================

    /* Allocation pointer points always to the next free ROB entry, it's the
     * available tag that is delivered to the scheduler */
    logic [PTR_WIDTH - 1:0] alloc_ptr, alloc_ptr_next;

    assign alloc_ptr_next = branch_flush_i ? branch_tag_i + 1'b1 :
                           (rob_alloc_i ? alloc_ptr + 1'b1 : alloc_ptr);

        always_ff @(posedge clk_i `ifdef ASYNC or negedge rst_n_i `endif) begin
            if (!rst_n_i) begin
                alloc_ptr <= '0;
            end else if (flush_i) begin
                alloc_ptr <= '0;
            end else begin
                alloc_ptr <= alloc_ptr_next;
            end
        end

    assign rob_tag_o = alloc_ptr;


//====================================================================================
//      ALLOCATION LOGIC
//====================================================================================

    /* Decode occupancy before the edge, away from writeback and bypass. */
        always_ff @(posedge clk_i `ifdef ASYNC or negedge rst_n_i `endif) begin
            if (!rst_n_i) begin
                empty_o <= 1'b1;
                full_o <= 1'b0;
            end else if (flush_i) begin
                empty_o <= 1'b1;
                full_o <= 1'b0;
            end else begin
                empty_o <= alloc_ptr_next == read_ptr_next;
                full_o <= (alloc_ptr_next[IDX_WIDTH - 1:0] == read_ptr_next[IDX_WIDTH - 1:0]) &
                          (alloc_ptr_next[IDX_WIDTH] != read_ptr_next[IDX_WIDTH]);
            end
        end


//====================================================================================
//      MEMORY LOGIC
//====================================================================================

    logic [$bits(rob_entry_t) - 1:0] reorder_buffer [ROB_DEPTH - 1:0];
    (* ram_style = "distributed" *) logic [31:0] allocated_pc [ROB_DEPTH - 1:0];

    initial begin
        for (int i = 0; i < ROB_DEPTH; ++i) begin
            reorder_buffer[i] = '0;
            allocated_pc[i] = '0;
        end
    end

        always_ff @(posedge clk_i) begin : rob_write_port
            if (write & !stall_i) begin
                reorder_buffer[tag_i[IDX_WIDTH - 1:0]] <= entry_i;
            end 
        end : rob_write_port

        always_ff @(posedge clk_i) begin : allocation_pc_write_port
            if (rob_alloc_i) begin
                allocated_pc[alloc_ptr[IDX_WIDTH - 1:0]] <= alloc_pc_i;
            end
        end : allocation_pc_write_port

    assign entry_o = reorder_buffer[read_ptr[IDX_WIDTH - 1:0]];
    assign head_pc_o = allocated_pc[read_ptr[IDX_WIDTH - 1:0]];


    logic [ROB_DEPTH - 1:0] valid;

        always_ff @(posedge clk_i `ifdef ASYNC or negedge rst_n_i `endif) begin
            if (!rst_n_i) begin
                valid <= '0;
            end else if (flush_i) begin
                valid <= '0;
            end else begin
                if (rob_alloc_i & !branch_flush_i) begin
                    /* Invalidate the slot being allocated as it holds
                     * no valid results */
                    valid[alloc_ptr[IDX_WIDTH - 1:0]] <= 1'b0;    
                end

                if (!stall_i) begin 
                    if (write) begin
                        /* Validate on write */
                        valid[tag_i[IDX_WIDTH - 1:0]] <= 1'b1;
                    end

                    if (read_i) begin
                        /* Invalidate on read */
                        valid[read_ptr[IDX_WIDTH - 1:0]] <= 1'b0;
                    end
                end
            end
        end
        
    assign valid_o = valid[read_ptr[IDX_WIDTH - 1:0]] & !empty_o;

    `ifdef SV_ASSERTION
        assert property (@(posedge clk_i) disable iff (!rst_n_i)
            empty_o == (alloc_ptr == read_ptr));

        assert property (@(posedge clk_i) disable iff (!rst_n_i)
            full_o == ((alloc_ptr[IDX_WIDTH - 1:0] == read_ptr[IDX_WIDTH - 1:0]) &
                       (alloc_ptr[IDX_WIDTH] != read_ptr[IDX_WIDTH])));
    `endif

endmodule : reorder_buffer

`endif
